common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  password:

development:
  <<: *common
  database: upsite_development

test:
  <<: *common
  database: upsite_test

production:
  <<: *common
  database: upsite_production
