# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cee39054ca000fe9daade499b90333ac7000898a135b6e7300e5631274c30288fe9ee9276cf1ddd17cf747f5b6fcc8b6771062b3ad7982758d982e3882460e9

test:
  secret_key_base: c6f804a21c361522fd29f892fe1b2767a6603cab459cbb63bfe99b0305e33e864e2f7cbe2e65648ed15bf093f66a58f39b35154d882ef5aacc371e51bcf06e5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
